// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gin-micro-example/internal/ioc"
	"gin-micro-example/internal/web"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	v := ioc.InitGinMiddlewares()
	userHandler := web.NewUserHandler()
	engine := ioc.InitWebServer(v, userHandler)
	return engine
}
