// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gin-micro-example/grpc"
	"gin-micro-example/internal/ioc"
	"gin-micro-example/internal/service"
	"gin-micro-example/internal/web"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	v := ioc.InitGinMiddlewares()
	userService := service.NewUserService()
	userServiceClient := ioc.InitUserClient()
	userHandler := web.NewUserHandler(userService, userServiceClient)
	engine := ioc.InitWebServer(v, userHandler)
	return engine
}

func InitGrpcServer() *AppGrpcServe {
	userService := service.NewUserService()
	userServiceServe := grpc.NewUserServiceServer(userService)
	server := ioc.NewGrpcServer(userServiceServe)
	appGrpcServe := &AppGrpcServe{
		server: server,
	}
	return appGrpcServe
}
